# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: Wine API
            description: API for managing wine measurements
            version: 1.0.0
        paths:
            /api/login:
                post:
                    summary: API Login
                    description: Login to obtain an authentication token.
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Successful operation
                            content:
                                application/xml:
                                    schema:
                                        type: string
                                application/json:
                                    schema:
                                        type: string
                        '400':
                            description: Invalid username/password supplied
                    tags:
                        - User
            /register:
                post:
                    description: Creates a new user
                    tags:
                        - User
            /logout:
                post:
                    description: User Logout
                    tags:
                        - User
            /api/sensor:
                post:
                    tags:
                        - Wine Management
                    summary: Register a new sensor
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                            description: New sensor name
                    responses:
                        '201':
                            description: Sensor created successfully
                        '400':
                            description: Bad request
            /api/sensors:
                get:
                    tags:
                        - Wine Management
                    summary: Get sorted sensors
                    responses:
                        '200':
                            description: Successful response
            /api/measurement:
                post:
                    tags:
                        - Wine Management
                    summary: Register a new measurement
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Measurement'
            /api/wines/measurements:
                get:
                    tags:
                        - Wine Management
                    summary: Get a list of wines with their measurements
                    description: "Returns a list of wines with their associated measurements"
                    responses:
                        200:
                            description: Successful response
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Measurement'
                        400:
                            description: "Bad request"
                        500:
                            description: "Server error"

        tags:
            - name: User
            - name: Wine Management
        components:
            schemas:
                Measurement:
                    type: object
                    properties:
                        year: { type: integer, example: 2024}
                        sensor_id: { type: integer, example: 1 }
                        wine_id: { type: integer, example: 1 }
                        wine_name: {type: string, example: Crianza }
                        color: { type: string, example: red }
                        temperature: { type: number, example: 18 }
                        alcoholContent: { type: number, example: 14 }
                        ph: { type: number, example: 5 }


    areas:
        path_patterns:
            - ^/api(?!/doc$) # Matches any path starting with /api except /api/doc
